version: "2"

linters:
  enable:
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - dupl
    - interfacebloat
    - errorlint
    - unparam
    - revive
    - gocritic
    - unconvert

  settings:
    gocyclo:
      min-complexity: 20
    gocognit:
      min-complexity: 30
    funlen:
      lines: 100
      statements: 60
    nestif:
      min-complexity: 6
    dupl:
      threshold: 160
    interfacebloat:
      max: 10

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gocognit
          - gocyclo
          - dupl
          - unparam
